# DAY12&13

### NUMPY LIBRARY

In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [6]:
a=np.array([1,2,3,4,5])
print(a.ndim)

b=np.array([[1,2,3],[4,5,6]])
print(b.ndim)

c=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c.ndim)

1
2
3


In [8]:
arr=np.array([1,2,3,4,5], ndmin=4)
print(arr,arr.ndim)

[[[[1 2 3 4 5]]]] 4


In [12]:
a=np.array([1,2,3,4,5])
print(a[2])

b=np.array([[1,2,3],[4,5,6]])
print(b[1,2])

c=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c[1,1,1])

3
6
8


In [15]:
a=np.array([1,2,3,4,5])
print(a[1:4])

b=np.array([[1,2,3],[4,5,6]])
print(b[1,1:3])

c=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c[1,0,0:1])

[2 3 4]
[5 6]
[5]


In [27]:
a=np.array([1,2,3,4,5])
print(a.dtype)

b=np.array([1.1,2.2,3.3,4.4,5.5])
print(b.dtype)

c=np.array([1,2,3,4,5], dtype='float64')
print(c.dtype)

int32
float64
float64


In [29]:
a=np.array([1,2,3,4,5])
print(a.shape) #elements

b=np.array([[1,2,3],[4,5,6]])
print(b.shape) #rows,elements

c=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c.shape) #plane,rows,elements

(5,)
(2, 3)
(2, 2, 2)


In [35]:
a=np.array([1,2,3,4,5])
b=np.array([1,2,3])
c=np.concatenate((a,b))
print(c)

x=np.array([[1,2,3],[4,5,6]])
y=np.array([[1,2,3],[4,5,6]])
z=np.concatenate((x,y), axis=1)
print(z)

[1 2 3 4 5 1 2 3]
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


In [38]:
a=np.array([1,2,3,4,5])
x=np.array_split(a,5)
print(x)

b=np.array([[1,2,3],[4,5,6]])
y=np.array_split(b,3)
print(y)

c=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
z=np.array_split(c,4)
print(z)

[array([1]), array([2]), array([3]), array([4]), array([5])]
[array([[1, 2, 3]]), array([[4, 5, 6]]), array([], shape=(0, 3), dtype=int32)]
[array([[[1, 2],
        [3, 4]]]), array([[[5, 6],
        [7, 8]]]), array([], shape=(0, 2, 2), dtype=int32), array([], shape=(0, 2, 2), dtype=int32)]


In [45]:
a=np.array([[1,2,3],[4,5,6]])
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [44]:
b=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
b.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [47]:
a=np.array([[1,2,3],[4,5,6]])
x=np.unique(a)
print(x)

b=np.array([[[1,2],[3,4]],[[3,2],[1,0]]])
y=np.unique(b)
print(y)

[1 2 3 4 5 6]
[0 1 2 3 4]


In [58]:
a=np.array([1,2,3,4,5])
x=np.delete(a,[2])
print(x)

b=np.array([[1,2,3],[4,5,6]])
y=np.delete(b,1,1)
print(y)

c=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
z=np.delete(c,1,1) #delete can take maximum 3 arguments 
print(z)

[1 2 4 5]
[[1 3]
 [4 6]]
[[[1 2]]

 [[5 6]]]
